import { PREVIEW_WIDTH_MOBILE } from '@/stores/preview'

export const XHS_PAGE_WIDTH = 720
export const XHS_PAGE_HEIGHT = 960
export const XHS_PREVIEW_WIDTH = 540
export const XHS_PREVIEW_SCALE = XHS_PREVIEW_WIDTH / XHS_PAGE_WIDTH
export const XHS_LAYOUT_SCALE = XHS_PAGE_WIDTH / PREVIEW_WIDTH_MOBILE
export const XHS_SOURCE_WIDTH = XHS_PAGE_WIDTH
export const XHS_SOURCE_PAGE_HEIGHT = XHS_PAGE_HEIGHT
export const XHS_EXPORT_MEDIA_MAX_WIDTH = 600
export const XHS_EXPORT_MEDIA_MAX_HEIGHT = 360
export const XHS_SOURCE_MEDIA_MAX_WIDTH = XHS_EXPORT_MEDIA_MAX_WIDTH
export const XHS_SOURCE_MEDIA_MAX_HEIGHT = XHS_EXPORT_MEDIA_MAX_HEIGHT
export const XHS_SOURCE_FOOTER_SAFE_AREA = Math.round(34 * XHS_LAYOUT_SCALE)
export const XHS_USABLE_PAGE_HEIGHT = XHS_SOURCE_PAGE_HEIGHT - XHS_SOURCE_FOOTER_SAFE_AREA
export const XHS_SPARSE_PAGE_HEIGHT = Math.round(112 * XHS_LAYOUT_SCALE)
export const XHS_PAGE_HEIGHT_TOLERANCE = 45
export const XHS_MIN_MEDIA_FIT_SCALE = 0.8
